backend:
  name: "github"
  repo: "detarkende/astro-netlifycms-starter"
  branch: "master"
media_folder: "/public/uploads"
public_folder: '/uploads'
collections:
  - name: "posts"
    slug: "{{slug}}"
    identifier_field: "slug"
    label: "Posts"
    folder: "src/pages/blog/posts"
    create: true
    preview_path: "blog/{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: '@/layouts/BlogPostLayout.astro', required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Short description", name: "short_description", widget: "string", required: true}
      - {label: "Publish Date", name: "publishedAt", widget: "datetime", required: true}
      - {label: "Featured Image", name: "image_url", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
